M48
; DRILL file {KiCad 7.0.1} date Wed Aug 21 14:43:35 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-21T14:43:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T1
X43.965Y-26.641
X43.965Y-28.673
X49.045Y-27.657
T2
X32.0Y-26.002
X53.997Y-62.0
T0
M30
